In [2]:
import pandas as pd
import numpy as np

In [79]:
df = pd.read_csv('survey_stack_overflow.csv', index_col = 'ResponseId' )
#index_col to set index when loading, instead of doing it later with set_index

In [70]:
df.shape

(83439, 47)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83439 entries, 1 to 83439
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   MainBranch                    83439 non-null  object
 1   Employment                    83323 non-null  object
 2   Country                       83439 non-null  object
 3   US_State                      14920 non-null  object
 4   UK_Country                    4418 non-null   object
 5   EdLevel                       83126 non-null  object
 6   Age1stCode                    83243 non-null  object
 7   LearnCode                     82963 non-null  object
 8   YearsCode                     81641 non-null  object
 9   YearsCodePro                  61216 non-null  object
 10  DevType                       66484 non-null  object
 11  OrgSize                       60726 non-null  object
 12  Currency                      61080 non-null  object
 13  CompTotal                     47183 non-null  float64
 14  CompFreq                      52150 non-null  object
 15  LanguageHaveWorkedWith        82357 non-null  object
 16  LanguageWantToWorkWith        76821 non-null  object
 17  DatabaseHaveWorkedWith        69546 non-null  object
 18  DatabaseWantToWorkWith        58299 non-null  object
 19  PlatformHaveWorkedWith        52135 non-null  object
 20  PlatformWantToWorkWith        41619 non-null  object
 21  WebframeHaveWorkedWith        61707 non-null  object
 22  WebframeWantToWorkWith        52095 non-null  object
 23  MiscTechHaveWorkedWith        47055 non-null  object
 24  MiscTechWantToWorkWith        38021 non-null  object
 25  ToolsTechHaveWorkedWith       72537 non-null  object
 26  ToolsTechWantToWorkWith       65480 non-null  object
 27  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 28  NEWCollabToolsWantToWorkWith  73022 non-null  object
 29  OpSys                         83294 non-null  object
 30  NEWStuck                      83052 non-null  object
 31  NEWSOSites                    83171 non-null  object
 32  SOVisitFreq                   82413 non-null  object
 33  SOAccount                     82525 non-null  object
 34  SOPartFreq                    67553 non-null  object
 35  SOComm                        82319 non-null  object
 36  NEWOtherComms                 82828 non-null  object
 37  Age                           82407 non-null  object
 38  Gender                        82286 non-null  object
 39  Trans                         80678 non-null  object
 40  Sexuality                     73366 non-null  object
 41  Ethnicity                     79464 non-null  object
 42  Accessibility                 77603 non-null  object
 43  MentalHealth                  76920 non-null  object
 44  SurveyLength                  81711 non-null  object
 45  SurveyEase                    81948 non-null  object
 46  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), object(45)
memory usage: 30.6+ MB

In [72]:
pd.set_option('display.max_columns',48)
df.head()

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [73]:
schema_df = pd.read_csv('survey_results_schema.csv')
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID24,Employment,Which of the following best describes your cur...,False,MC,MAVR
...,...,...,...,...,...,...
43,QID124,Accessibility,"Which of the following describe you, if any? P...",False,MC,MAVR
44,QID125,MentalHealth,"Which of the following describe you, if any? P...",False,MC,MAVR
45,QID131,S6,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
46,QID132,SurveyLength,How do you feel about the length of the survey...,False,MC,MAVR
47,QID133,SurveyEase,How easy or difficult was this survey to compl...,False,MC,MAVR

In [74]:
df_arg = df.copy()[df['Country'] == 'Argentina']

df_arg

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
290,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,25 - 34 years,Coding Bootcamp;Other online resources (ex: vi...,5,Less than 1 year,"Developer, full-stack",20 to 99 employees,USD\tUnited States dollar,75000.0,Yearly,HTML/CSS;JavaScript;Node.js;Python;Ruby;SQL;Ty...,HTML/CSS;JavaScript;Ruby;TypeScript,Firebase;MySQL,PostgreSQL,Google Cloud Platform;Heroku,AWS;Google Cloud Platform;Heroku,jQuery;React.js;Ruby on Rails,jQuery;React.js;Ruby on Rails,React Native,React Native,Docker;Git;Yarn,Docker;Git;Yarn,Sublime Text;Visual Studio Code,Sublime Text;Visual Studio Code,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, somewhat",Yes,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Appropriate in length,Easy,75000.0
484,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Other (please specify):,20,18,"Developer, back-end",20 to 99 employees,ARS\tArgentine peso,17250000.0,Yearly,C#;HTML/CSS;JavaScript;Node.js;TypeScript,C#;HTML/CSS;JavaScript;Node.js;TypeScript,Microsoft SQL Server,NaN,Microsoft Azure,Google Cloud Platform;Microsoft Azure,ASP.NET;ASP.NET Core ;Vue.js,Express;React.js,.NET Framework;.NET Core / .NET 5,.NET Core / .NET 5,Docker;Git,Docker;Git,Visual Studio;Visual Studio Code,Visual Studio Code,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, definitely",Yes,35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,NaN,None of the above,Appropriate in length,Easy,279774.0
1046,I am a student who is learning to code,"Not employed, but looking for work",Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",3,NaN,"Developer, back-end",NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;Node.js;PHP;SQL;Ty...,NaN,MariaDB;Microsoft SQL Server;MongoDB;MySQL,NaN,Heroku,NaN,ASP.NET;jQuery;Vue.js,NaN,.NET Framework,NaN,Docker;Git,NaN,Visual Studio Code,NaN,Windows,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,Neutral,No,18-24 years old,Man,No,Straight / Heterosexual,I don't know,None of the above,None of the above,Appropriate in length,Easy,NaN
1202,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Argentina,NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",17,14,"Developer, front-end",100 to 499 employees,USD\tUnited States dollar,100000.0,Yearly,JavaScript;TypeScript,TypeScript,NaN,NaN,NaN,NaN,React.js,React.js,NaN,NaN,Git,Git,Visual Studio Code,Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",No,35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,100000.0
1327,"I am not primarily a developer, but I write co...",Employed full-time,Argentina,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",15,15,Academic researcher,"10,000 or more employees",ARS\tArgentine peso,72000.0,Monthly,Python;R,C;Python,NaN,NaN,NaN,NaN,NaN,NaN,NumPy,NumPy;TensorFlow;Torch/PyTorch,NaN,NaN,Sublime Text,Sublime Text;Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Appropriate in length,Easy,14016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83021,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,5 - 10 years,Books / Physical media,15,14,"Developer, full-stack;Engineer, site reliability",500 to 999 employees,USD\tUnited States dollar,4700.0,Monthly,Go;JavaScript;Node.js;Python;Scala;TypeScript,Go;Python;Rust,MongoDB;Redis,PostgreSQL;Redis;SQLite,AWS;Microsoft Azure,AWS,Express;Flask,Django;Flask,NaN,NaN,Docker;Git;Kubernetes;Terraform,Docker;Git;Kubernetes;Terraform,Vim,Vim,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,A few times per month or weekly,"Yes, somewhat",Yes,25-34 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,I have an anxiety disorder,Too long,Easy,56400.0
83122,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Argentina,NaN,NaN,"Professional degree (JD, MD, etc.)",25 - 34 years,"Other online resources (ex: videos, blogs, etc...",35,25,"Developer, mobile;Developer, front-end;Develop...",2 to 9 employees,ARS\tArgentine peso,250000.0,Monthly,C;C#;C++;HTML/CSS;JavaScript;SQL,Node.js;Python;R;SQL,MariaDB;Microsoft SQL Server;SQLite,Elasticsearch;Microsoft SQL Server;MongoDB,Microsoft Azure,Microsoft Azure,Angular.js;ASP.NET,Angular.js;ASP.NET Core ;React.js,.NET Framework;Qt,.NET Core / .NET 5;Apache Spark;Hadoop,Git;Unity 3D;Xamarin,Docker;Git;Kubernetes;Unity 3D;Xamarin,Android Studio;Visual Studio;Visual Studio Code,Android Studio;Visual Studio;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,No,45-54 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,48660.0
83196,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,18 - 24 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, front-end",100 to 499 employees,USD\tUnited States dollar,1800.0,Monthly,HTML/CSS;JavaScript;Node.js,HTML/CSS;JavaScript;Node.js;Python;TypeScript,NaN,NaN,NaN,NaN,React.js,Angular;Django;Express,NaN,NaN,Git,Docker;Git;Kubernetes,Visual Studio Code,Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per week,Not sure/can't remember,NaN,"No, not really",No,25-34 years old,Man,No,Gay or Lesbian,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21600.0
83269,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",9,6,"Developer, front-end;Developer, full-stack;Dev...",100 to 499 employees,ARS\tArgentine peso,250000.0,Monthly,Bash/Shell;C#;F#;Haskell;HTML/CSS;Java;JavaScr...,Bash/Shell;C#;F#;Haskell;HTML/CSS;Java;JavaScr...,PostgreSQL;SQLite,MariaDB;MongoDB;PostgreSQL;Redis,NaN,NaN,Angular;ASP.NET;ASP.NET Core ;jQuery;React.js;...,ASP.NET Core ;React.js;Spring,.NET Framework;.NET Core / .NET 5;React Native,.NET Core / .NET 5;React Native,Git,Git,Android Studio;Sublime Text;Visual Studio;Visu...,IntelliJ;Sublime Text;Visual Studio;Visual Stu...,Windows,Call a coworker or friend;Go for a walk or oth...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,48660.0
83380,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,6,5,"Developer, full-stack;Designer",100 to 499 employees,ARS\tArgentine peso,NaN,Monthly,C#;HTML/CSS;JavaScript;Node.js;Python;SQL;Type...,C#;Go;JavaScript;Node.js;SQL;TypeScript,MongoDB;PostgreSQL,PostgreSQL,AWS,AWS;Microsoft Azure,Angular;ASP.NET Core ;Express;React.js,ASP.NET Core ;Express;React.js,.NET Core / .NET 5;React Native,.NET Core / .NET 5;Flutter;TensorFlow,Docker;Git,Docker;Git,IPython/Jupyter;Visual Studio;Visual Studio Code,Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",Yes,25-34 years old,Woman,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,NaN,I have a concentration and/or memory disorder ...,Too short,Easy,NaN

In [75]:
df_arg['EdLevel'].value_counts()

Some college/university study without earning a degree                                228
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          146
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     82
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        45
Professional degree (JD, MD, etc.)                                                     30
Associate degree (A.A., A.S., etc.)                                                    28
Primary/elementary school                                                              11
Other doctoral degree (Ph.D., Ed.D., etc.)                                              9
Something else                                                                          8
Name: EdLevel, dtype: int64

In [76]:
df_arg.loc[0:83379,'ConvertedCompYearly'].sum()/len(df_arg)
# not discarding the NaN values (so it's a higher value)

32123.30834752981

In [77]:
df_arg.set_index('ConvertedCompYearly')
#change indexing
#inplace = True to save changes to df and not just display them once

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase
ConvertedCompYearly,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
75000.0,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,25 - 34 years,Coding Bootcamp;Other online resources (ex: vi...,5,Less than 1 year,"Developer, full-stack",20 to 99 employees,USD\tUnited States dollar,75000.0,Yearly,HTML/CSS;JavaScript;Node.js;Python;Ruby;SQL;Ty...,HTML/CSS;JavaScript;Ruby;TypeScript,Firebase;MySQL,PostgreSQL,Google Cloud Platform;Heroku,AWS;Google Cloud Platform;Heroku,jQuery;React.js;Ruby on Rails,jQuery;React.js;Ruby on Rails,React Native,React Native,Docker;Git;Yarn,Docker;Git;Yarn,Sublime Text;Visual Studio Code,Sublime Text;Visual Studio Code,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, somewhat",Yes,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Appropriate in length,Easy
279774.0,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Other (please specify):,20,18,"Developer, back-end",20 to 99 employees,ARS\tArgentine peso,17250000.0,Yearly,C#;HTML/CSS;JavaScript;Node.js;TypeScript,C#;HTML/CSS;JavaScript;Node.js;TypeScript,Microsoft SQL Server,NaN,Microsoft Azure,Google Cloud Platform;Microsoft Azure,ASP.NET;ASP.NET Core ;Vue.js,Express;React.js,.NET Framework;.NET Core / .NET 5,.NET Core / .NET 5,Docker;Git,Docker;Git,Visual Studio;Visual Studio Code,Visual Studio Code,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, definitely",Yes,35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,NaN,None of the above,Appropriate in length,Easy
NaN,I am a student who is learning to code,"Not employed, but looking for work",Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",3,NaN,"Developer, back-end",NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;Node.js;PHP;SQL;Ty...,NaN,MariaDB;Microsoft SQL Server;MongoDB;MySQL,NaN,Heroku,NaN,ASP.NET;jQuery;Vue.js,NaN,.NET Framework,NaN,Docker;Git,NaN,Visual Studio Code,NaN,Windows,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,Neutral,No,18-24 years old,Man,No,Straight / Heterosexual,I don't know,None of the above,None of the above,Appropriate in length,Easy
100000.0,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Argentina,NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",17,14,"Developer, front-end",100 to 499 employees,USD\tUnited States dollar,100000.0,Yearly,JavaScript;TypeScript,TypeScript,NaN,NaN,NaN,NaN,React.js,React.js,NaN,NaN,Git,Git,Visual Studio Code,Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",No,35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy
14016.0,"I am not primarily a developer, but I write co...",Employed full-time,Argentina,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",15,15,Academic researcher,"10,000 or more employees",ARS\tArgentine peso,72000.0,Monthly,Python;R,C;Python,NaN,NaN,NaN,NaN,NaN,NaN,NumPy,NumPy;TensorFlow;Torch/PyTorch,NaN,NaN,Sublime Text,Sublime Text;Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56400.0,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,5 - 10 years,Books / Physical media,15,14,"Developer, full-stack;Engineer, site reliability",500 to 999 employees,USD\tUnited States dollar,4700.0,Monthly,Go;JavaScript;Node.js;Python;Scala;TypeScript,Go;Python;Rust,MongoDB;Redis,PostgreSQL;Redis;SQLite,AWS;Microsoft Azure,AWS,Express;Flask,Django;Flask,NaN,NaN,Docker;Git;Kubernetes;Terraform,Docker;Git;Kubernetes;Terraform,Vim,Vim,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,A few times per month or weekly,"Yes, somewhat",Yes,25-34 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,I have an anxiety disorder,Too long,Easy
48660.0,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Argentina,NaN,NaN,"Professional degree (JD, MD, etc.)",25 - 34 years,"Other online resources (ex: videos, blogs, etc...",35,25,"Developer, mobile;Developer, front-end;Develop...",2 to 9 employees,ARS\tArgentine peso,250000.0,Monthly,C;C#;C++;HTML/CSS;JavaScript;SQL,Node.js;Python;R;SQL,MariaDB;Microsoft SQL Server;SQLite,Elasticsearch;Microsoft SQL Server;MongoDB,Microsoft Azure,Microsoft Azure,Angular.js;ASP.NET,Angular.js;ASP.NET Core ;React.js,.NET Framework;Qt,.NET Core / .NET 5;Apache Spark;Hadoop,Git;Unity 3D;Xamarin,Docker;Git;Kubernetes;Unity 3D;Xamarin,Android Studio;Visual Studio;Visual Studio Code,Android Studio;Visual Studio;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,No,45-54 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy
21600.0,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,18 - 24 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, front-end",100 to 499 employees,USD\tUnited States dollar,1800.0,Monthly,HTML/CSS;JavaScript;Node.js,HTML/CSS;JavaScript;Node.js;Python;TypeScript,NaN,NaN,NaN,NaN,React.js,Angular;Django;Express,NaN,NaN,Git,Docker;Git;Kubernetes,Visual Studio Code,Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per week,Not sure/can't remember,NaN,"No, not really",No,25-34 years old,Man,No,Gay or Lesbian,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy
48660.0,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",9,6,"Developer, front-end;Developer, full-stack;Dev...",100 to 499 employees,ARS\tArgentine peso,250000.0,Monthly,Bash/Shell;C#;F#;Haskell;HTML/CSS;Java;JavaScr...,Bash/Shell;C#;F#;Haskell;HTML/CSS;Java;JavaScr...,PostgreSQL;SQLite,MariaDB;MongoDB;PostgreSQL;Redis,NaN,NaN,Angular;ASP.NET;ASP.NET Core ;jQuery;React.js;...,ASP.NET Core ;React.js;Spring,.NET Framework;.NET Core / .NET 5;React Native,.NET Core / .NET 5;React Native,Git,Git,Android Studio;Sublime Text;Visual Studio;Visu...,IntelliJ;Sublime Text;Visual Studio;Visual Stu...,Windows,Call a coworker or friend;Go for a walk or oth...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy
NaN,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,Some college/university study without earning ...,18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,6,5,"Developer, full-stack;Designer",100 to 499 employees,ARS\tArgentine peso,NaN,Monthly,C#;HTML/CSS;JavaScript;Node.js;Python;SQL;Type...,C#;Go;JavaScript;Node.js;SQL;TypeScript,MongoDB;PostgreSQL,PostgreSQL,AWS,AWS;Microsoft Azure,Angular;ASP.NET Core ;Express;React.js,ASP.NET Core ;Express;React.js,.NET Core / .NET 5;React Native,.NET Core / .NET 5;Flutter;TensorFlow,Docker;Git,Docker;Git,IPython/Jupyter;Visual Studio;Visual Studio Code,Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",Yes,25-34 years old,Woman,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,NaN,I have a concentration and/or memory disorder ...,Too short,Easy

In [67]:
#df_arg.reset_index(inplace = True)

In [87]:
filt_py = (df['LanguageHaveWorkedWith'] == 'Python')
df_arg[filt_py]

<ipython-input-87-6607806d7333>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_arg[filt_py]

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
9255,I am a student who is learning to code,"Student, full-time",Argentina,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,Online Forum;Online Courses or Certification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Python,C;C++;Python,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Google it,Stack Overflow,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",No,18-24 years old,"Or, in your own words:","Or, in your own words:",Straight / Heterosexual;Prefer to self-describe:,"Hispanic or Latino/a/x;Or, in your own words:",NaN,NaN,NaN,NaN,NaN
10313,I code primarily as a hobby,"Student, part-time",Argentina,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,Python,C#;Dart;HTML/CSS;Node.js,SQLite,MongoDB;MySQL,NaN,NaN,NaN,NaN,NaN,NaN,Git,NaN,Visual Studio Code,Android Studio;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow,Daily or almost daily,Yes,Less than once per month or monthly,Neutral,No,18-24 years old,Man,No,NaN,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
21299,"I am not primarily a developer, but I write co...","Student, full-time",Argentina,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Friend or family member;Colleague,2,NaN,NaN,NaN,NaN,NaN,NaN,Python,C++;Julia;Python;SQL,NaN,NaN,NaN,NaN,NaN,NaN,Keras;NumPy;Pandas;TensorFlow,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,Visual Studio Code,Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,Neutral,No,25-34 years old,Woman,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
27474,None of these,"Student, full-time",Argentina,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School;Friend or family member,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,Python,NaN,NaN,NaN,Google Cloud Platform,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Google it,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,No,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Too long,Neither easy nor difficult,NaN
28067,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",20,15,"Developer, full-stack;Developer, back-end;Educ...",2 to 9 employees,USD\tUnited States dollar,2500.0,Monthly,Python,Go,MongoDB;MySQL;PostgreSQL;Redis;SQLite,DynamoDB;Elasticsearch,AWS,NaN,Django;jQuery,Django;React.js;Vue.js,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,PyCharm;Visual Studio Code,PyCharm;Webstorm,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,"Yes, somewhat",Yes,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Too long,Easy,30000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50255,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,Online Courses or Certification;Colleague;Book...,17,11,"Developer, back-end",20 to 99 employees,ARS\tArgentine peso,960000.0,Monthly,Python,C;C++;JavaScript,DynamoDB;MongoDB;MySQL;PostgreSQL;Redis,Elasticsearch;MySQL;PostgreSQL;Redis,AWS,AWS,Django;Flask,Django;FastAPI;React.js;Ruby on Rails,NaN,NaN,Docker;Git,Docker;Git;Terraform,IPython/Jupyter,IPython/Jupyter;PyCharm;Visual Studio Code,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",Yes,35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,186840.0
57004,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",18,11,Engineering manager,"1,000 to 4,999 employees",ARS\tArgentine peso,1000000.0,Yearly,Python,Python;Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,NumPy;Pandas,Docker;Git,Docker;Git;Kubernetes,Visual Studio Code,Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Overflow for Teams (priva...,A few times per month or weekly,Not sure/can't remember,NaN,"No, not really",No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,16219.0
66037,"I am not primarily a developer, but I write co...",Employed full-time,Argentina,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Friend or family member;Online Courses or Cert...,5,3,Data scientist or machine learning specialist,"5,000 to 9,999 employees",ARS\tArgentine peso,3875000.0,Yearly,Python,F#;Haskell;Julia;Kotlin;Python;Scala,Microsoft SQL Server;MySQL;PostgreSQL,Cassandra;DynamoDB;MongoDB;MySQL;PostgreSQL,AWS;Google Cloud Platform,AWS;Microsoft Azure,FastAPI,FastAPI,Keras;NumPy;Pandas,Apache Spark;Keras;NumPy;Pandas;TensorFlow;Tor...,Docker;Git,Docker;Git;Kubernetes,IPython/Jupyter;Neovim;PyCharm;Vim;Visual Stud...,IPython/Jupyter;Neovim;Vim;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,No,NaN,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,Multiracial;Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,62848.0
67015,I am a developer by profession,Employed full-time,Argentina,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",30,23,"Developer, full-stack",100 to 499 employees,ARS\tArgentine peso,115000.0,Monthly,Python,JavaScript;Python,MySQL,MySQL,AWS,AWS,Django;Flask,Django;Express;FastAPI;Flask;React.js,NaN,NaN,Git,Git,IPython/Jupyter;Notepad++;Visual Studio Code,IPython/Jupyter;Notepad++;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow,A few times per month or weekly,No,NaN,Neutral,No,55-64 years old,Man,No,NaN,White or of European descent;Hispanic or Latin...,None of the above,None of the above,Appropriate in length,Easy,22380.0
71917,"I am not primarily a developer, but I write co...",Employed full-time,Argentina,NaN,NaN,"Secondary school (e.g. American high school, G...",35 - 44 years,"Other online resources (ex: videos, blogs, etc...",3,2,Other (please specify):,"10,000 or more employees",ARS\tArgentine peso,NaN,NaN,Python,Go;HTML/CSS;JavaScript;Python,DynamoDB;MySQL,MySQL,AWS,AWS,Flask,FastAPI;Flask;Vue.js,NaN,NaN,Docker;Terraform,Docker;Kubernetes;Terraform,Visual Studio Code,Visual Studio Code,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,A few times per month or weekly,No,NaN,Not sure,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN

In [144]:
pd.set_option('display.max_rows',20)
df_ds_notnan = df[(df['DevType'] == 'Data scientist or machine learning specialist') & 
   (df['MainBranch'] == 'I am a developer by profession') &
   (df['ConvertedCompYearly'].notnull()) &
   (df['LanguageHaveWorkedWith'].str.contains('Python'))]
df_ds_notnan

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,4,Data scientist or machine learning specialist,10 to 19 employees,SEK\tSwedish krona,42000.0,Monthly,C++;Python,Haskell;Python,PostgreSQL,NaN,NaN,NaN,NaN,NaN,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;TensorFlow;Torch/PyTorch,Git,Git,IPython/Jupyter;Vim;Visual Studio Code,Emacs;IPython/Jupyter;Vim;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Daily or almost daily,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0
78,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",5 - 10 years,Friend or family member,10,8,Data scientist or machine learning specialist,500 to 999 employees,CAD\tCanadian dollar,200000.0,Yearly,HTML/CSS;Python;R,HTML/CSS;Python;R;Rust,DynamoDB,DynamoDB,AWS,AWS,Flask,Flask,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Apache Spark;Keras;NumPy;Pandas;TensorFlow;Tor...,Docker;Git,Docker;Git;Kubernetes,Atom;IPython/Jupyter;Notepad++;RStudio;Sublime...,Atom;IPython/Jupyter;RStudio;Sublime Text,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",Yes,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,151263.0
225,I am a developer by profession,Employed full-time,Belgium,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",12,9,Data scientist or machine learning specialist,"1,000 to 4,999 employees",EUR European Euro,70000.0,Yearly,Python,JavaScript;Julia;Python,NaN,NaN,NaN,NaN,NaN,NaN,Keras;NumPy;Pandas;TensorFlow,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Docker;Git,Docker;Git;Kubernetes;Terraform,IPython/Jupyter;Visual Studio Code,IPython/Jupyter;Visual Studio Code,Other (please specify):,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",Yes,35-44 years old,Man,No,Prefer to self-describe:,White or of European descent,NaN,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,75669.0
379,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",12,5,Data scientist or machine learning specialist,2 to 9 employees,INR\tIndian rupee,1300000.0,Monthly,C++;HTML/CSS;Java;JavaScript;PHP;Python;SQL,C++;Python,Elasticsearch;MongoDB;MySQL;Oracle,NaN,AWS;Google Cloud Platform,Google Cloud Platform,Angular;Angular.js,Flask,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Docker;Git,Docker;Git;Kubernetes,IPython/Jupyter;Notepad++;TextMate;Visual Studio,IPython/Jupyter;Notepad++;TextMate;Visual Studio,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,217800.0
587,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,Less than 1 year,Data scientist or machine learning specialist,"5,000 to 9,999 employees",INR\tIndian rupee,500000.0,Yearly,HTML/CSS;JavaScript;Python,Python;SQL,NaN,NaN,AWS,AWS,ASP.NET,Flask,NumPy;Pandas,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,NaN,None of the above,None of the above,Too long,Neither easy nor difficult,6981.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82274,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Books / Physical media,11,4,Data scientist or machine learning specialist,500 to 999 employees,INR\tIndian rupee,1700000.0,Yearly,Python;SQL,Python;SQL,MySQL;PostgreSQL,MySQL;PostgreSQL,AWS;Microsoft Azure,AWS;Google Cloud Platform;Microsoft Azure,NaN,NaN,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Docker;Git,Docker;Flow;Git;Kubernetes,Atom;IPython/Jupyter;Visual Studio Code,Atom;IPython/Jupyter;Visual Studio Code,MacOS,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",Yes,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,23735.0
82760,I am a developer by profession,Employed full-time,Netherlands,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,Books / Physical media,27,27,Data scientist or machine learning specialist,"10,000 or more employees",EUR European Euro,75000.0,Yearly,Java;Python,Java;Python;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,Keras;NumPy;Pandas,Git,Git,Eclipse;Notepad++,Eclipse;Notepad++;PyCharm,Windows,Google it;Do other work and come back later,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",No,55-64 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,81074.0
82907,I am a developer by profession,Employed full-time,Spain,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",12,6,Data scientist or machine learning specialist,20 to 99 employees,EUR European Euro,50000.0,Yearly,HTML/CSS;Python;R;SQL,Bash/Shell;Haskell;Julia;Python;Scala;SQL,Microsoft SQL Server;MongoDB;MySQL;Oracle;Post...,Microsoft SQL Server;MongoDB;MySQL;Oracle;Post...,AWS,AWS;Google Cloud Platform;Microsoft Azure,Django;FastAPI;Flask,Django;FastAPI;Flask,Apache Spark;Hadoop;NumPy;Pandas;TensorFlow;To...,Apache Spark;NumPy;Pandas;TensorFlow;Torch/PyT...,Docker;Git,Docker;Git,IPython/Jupyter;RStudio;Sublime Text;Visual St...,IPython/Jupyter;Sublime Text;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, somewhat",Yes,25-34 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,54049.0
82922,I am a developer by profession,Employed full-time,Colombia,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",5 - 10 years,Coding Bootcamp,22,17,Data scientist or machine learning specialist,"10,000 or more employees",COP\tColombian peso,12700000.0,Monthly,Python;R,NaN,MySQL;PostgreSQL,NaN,DigitalOcean;Heroku,AWS,FastAPI,NaN,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,Git,Docker,IPython/Jupyter;Visual Studio Code,NaN,Linux-based,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",No,35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,44844.0
83113,I am a developer by profession,Employed full-time,United States of America,North Carolina,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Online Forum;Friend or family member,9,4,Data scientist or machine learning specialist,"5,000 to 9,999 employees",USD\tUnited States dollar,88550.0,Yearly,Bash/Shell;Perl;Python;R,Bash/Shell;Python;R,MySQL,MySQL,AWS,AWS,NaN,NaN,Keras;NumPy;Pandas,NumPy;Pandas,Git,Docker;Git,IPython/Jupyter;PyCharm;RStudio;Sublime Text,IPython/Jupyter;PyCharm;RStudio,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,88550.0

In [145]:
df_ds_notnan['ConvertedCompYearly'].sum()/len(df_ds_notnan)

121389.26702997275

In [147]:
df_ds_notnan.sort_values('ConvertedCompYearly')[120:135]

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
18347,I am a developer by profession,Employed full-time,Italy,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",10,3,Data scientist or machine learning specialist,20 to 99 employees,EUR European Euro,33000.0,Yearly,Go;HTML/CSS;JavaScript;LISP;Matlab;Python;SQL,Go;LISP;Node.js;Python;SQL,PostgreSQL;SQLite,Elasticsearch;Redis;SQLite,AWS;Google Cloud Platform,AWS,Django,FastAPI,NumPy;Pandas;TensorFlow;Torch/PyTorch,Hadoop;NumPy;Pandas;TensorFlow;Torch/PyTorch,Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Emacs;IPython/Jupyter;Vim;Visual Studio Code,Emacs;IPython/Jupyter;Vim;Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",Yes,25-34 years old,Man,No,Prefer not to say,White or of European descent,None of the above,Prefer not to say,Appropriate in length,Easy,35672.0
40784,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",8,2,Data scientist or machine learning specialist,"10,000 or more employees",INR\tIndian rupee,2600000.0,Yearly,C#;Python,Python,NaN,NaN,Microsoft Azure,Microsoft Azure,NaN,NaN,NumPy;Pandas;Torch/PyTorch,Torch/PyTorch,Git;Yarn,Docker;Git,Visual Studio;Visual Studio Code,Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,18-24 years old,Man,No,Straight / Heterosexual,South Asian,I am unable to / find it difficult to walk or ...,None of the above,Too short,Easy,36300.0
47977,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",9,2,Data scientist or machine learning specialist,"1,000 to 4,999 employees",INR\tIndian rupee,2600000.0,Yearly,Python,Clojure;Go;Python,NaN,NaN,Microsoft Azure,NaN,NaN,NaN,NumPy;Pandas;Torch/PyTorch,Apache Spark;NumPy;Pandas;Torch/PyTorch,Git,Git,PyCharm;Visual Studio Code,PyCharm;Visual Studio Code,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual;Bisexual,South Asian,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,36300.0
43677,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Friend or family member;Online Courses ...,4,Less than 1 year,Data scientist or machine learning specialist,"1,000 to 4,999 employees",CAD\tCanadian dollar,48000.0,Yearly,HTML/CSS;Java;JavaScript;Matlab;Python,HTML/CSS;Java;JavaScript;Python;TypeScript,Microsoft SQL Server;MySQL;Redis,Microsoft SQL Server;MongoDB;MySQL;Redis,AWS;DigitalOcean;Microsoft Azure,AWS;Microsoft Azure,React.js,React.js,NumPy;Pandas;Qt;Torch/PyTorch,NumPy;Pandas;Qt;Torch/PyTorch,NaN,NaN,IntelliJ;PyCharm;Visual Studio Code,IntelliJ;PyCharm;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,No,18-24 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,36303.0
56233,I am a developer by profession,Employed part-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",4,3,Data scientist or machine learning specialist,2 to 9 employees,EUR European Euro,2800.0,Monthly,Bash/Shell;C;C++;HTML/CSS;Matlab;Python,JavaScript,MongoDB,PostgreSQL,NaN,NaN,NaN,NaN,Keras;NumPy;TensorFlow,Keras;NumPy;TensorFlow,Docker;Git,Docker;Git,Neovim;PyCharm,Neovim;PyCharm,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,No,NaN,"No, not really",Yes,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,36324.0
68304,I am a developer by profession,Employed full-time,Italy,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",10,7,Data scientist or machine learning specialist,20 to 99 employees,EUR European Euro,34000.0,Yearly,Python;SQL,Haskell;Java;Python,Microsoft SQL Server;MongoDB;MySQL,NaN,Microsoft Azure,NaN,NaN,NaN,Keras;NumPy;Pandas;TensorFlow,Hadoop;Keras;NumPy;Pandas;TensorFlow,NaN,NaN,IPython/Jupyter,IPython/Jupyter,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too long,Easy,36753.0
65711,I am a developer by profession,Employed part-time,Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,15,8,Data scientist or machine learning specialist,20 to 99 employees,EUR European Euro,2850.0,Monthly,Bash/Shell;HTML/CSS;Java;Python;R;SQL,Bash/Shell;HTML/CSS;JavaScript;Python;R;SQL,MongoDB;MySQL;Oracle;PostgreSQL,MongoDB;MySQL;PostgreSQL,AWS;Google Cloud Platform,AWS;Google Cloud Platform,Flask,Flask,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,Docker;Git;Terraform,Docker;Git;Terraform,IPython/Jupyter;PyCharm;Visual Studio Code,IPython/Jupyter;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,36972.0
42216,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",6,3,Data scientist or machine learning specialist,500 to 999 employees,INR\tIndian rupee,2700000.0,Yearly,C;Python;Scala;SQL,Node.js;R,DynamoDB;Elasticsearch;MongoDB;MySQL;Redis,PostgreSQL;SQLite,AWS;Google Cloud Platform,Google Cloud Platform;Microsoft Azure,Flask,FastAPI;Flask,Apache Spark;Keras;NumPy;Pandas;TensorFlow;Tor...,Keras;Torch/PyTorch,Docker,Docker;Kubernetes,IPython/Jupyter;PyCharm,IPython/Jupyter;PyCharm,Linux-based,Visit Stack Overflow;Google it;Play games,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,Neutral,No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,37697.0
80890,I am a developer by profession,Employed full-time,Poland,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,4,3,Data scientist or machine learning specialist,"10,000 or more employees",PLN\tPolish zloty,12500.0,Monthly,Python;SQL,Python;SQL,Cassandra;MySQL;Oracle;PostgreSQL,NaN,AWS,AWS,NaN,NaN,Apache Spark;Hadoop;NumPy;Pandas,Apache Spark;Hadoop;NumPy;Pandas,NaN,NaN,IPython/Jupyter,IPython/Jupyter,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have an anxiety disorder,Appropriate in length,Easy,37968.0
33253,I am a developer by profession,Employed full-time,France,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",7,2,Data scientist or machine learning specialist,100 to 499 employees,EUR European Euro,36000.0,Yearly,C++;Python,C++;Python;Rust,NaN,NaN,Google Cloud Platform,NaN,NaN,NaN,NumPy;Pandas;Torch/PyTorch,NumPy;Pandas;Torch/PyTorch,Docker,Docker;Kubernetes;Unity 3D,Vim;Visual Studio Code,Vim;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Less than once per month or monthly,Neutral,Yes,25-34 years old,Man,No,Straight / Heterosexual,"Or, in your own words:",None of the above,None of the above,Appropriate in length,Easy,38915.0
38693,I am a developer by profession,"Independent contractor, freelancer, or self-em...",France,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,School,8,5,Data scientist or machine learning specialist,"Just me - I am a freelancer, sole proprietor, ...",EUR European Euro,3000.0,Monthly,C;C#;C++;HTML/CSS;Java;JavaScript;Python;SQL,Java;JavaScript;Python;SQL,Elasticsearch;PostgreSQL,Elasticsearch;PostgreSQL,AWS;Heroku,NaN,Django;Flask;React.js,Django;Flask;React.js,Apache Spark;Keras;NumPy;Pandas;Qt;TensorFlow,Apache Spark;Keras;NumPy;Pandas;Qt;TensorFlow;...,NaN,NaN,Emacs;IntelliJ;IPython/Jupyter;PyCharm;Visual ...,Emacs;IntelliJ;IPython/Jupyter;PyCharm,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,NaN,Too long,Easy,38916.0
74856,I am a developer by profession,Employed full-time,Poland,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,School;Online Forum;Online Courses or Certific...,5,3,Data scientist or machine learning specialist,I don’t know,PLN\tPolish zloty,13000.0,Monthly,Python;SQL,C++;Python;Scala,Microsoft SQL Server,MongoDB;PostgreSQL;Redis,NaN,NaN,Flask,Django;Flask,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorF...,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorF...,Git,Docker;Git;Kubernetes;Yarn,IPython/Jupyter;Notepad++,Atom;PyCharm,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, definitely",Yes,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,39492.0
14550,I am a developer by profession,Employed full-time,Bulgaria,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Books / Physical media,15,12,Data scientist or machine learning specialist,500 to 999 employees,BGN\tBulgarian lev,6000.0,Monthly,Python,Python;Rust,PostgreSQL,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,NaN,Pandas;Torch/PyTorch,TensorFlow;Torch/PyTorch,Git,Docker;Git;Kubernetes,PyCharm,IntelliJ;PyCharm,MacOS,Go for a walk or other physical activity;Googl...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",Yes,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too short,Easy,39780.0
838,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,"Other online resources (ex: videos, blogs, etc)",10,2,Data scientist or machine learning specialist,"1,000 to 4,999 employees",EUR European Euro,3100.0,Monthly,Python;R;SQL,Python;R;SQL,MySQL;PostgreSQL;SQLite,PostgreSQL,AWS;Google Cloud Platform,AWS;Google Cloud Platform,NaN,NaN,Apache Spark;NumPy;Pandas;TensorFlow,NumPy;Pandas;TensorFlow,Docker,Docker,IPython/Jupyter;PyCharm;RStudio,IPython/Jupyter;PyCharm;RStudio,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,A few times per week,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,40212.0
45286,I am a developer by profession,Employed full-time,Netherlands,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",10,5,Data scientist or machine learning specialist,20 to 99 employees,EUR European Euro,3100.0,Monthly,C#;Python;TypeScript,C#,MongoDB,NaN,NaN,NaN,Angular,NaN,.NET Framework;.NET Core / .NET 5,.NET Framework;.NET Core / .NET 5,Git,Git;Unity 3D,IPython/Jupyter;Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Call a coworker or friend;Google it;Do other w...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,40212.0

In [149]:
#df.columns = [x.lower() for x in df.columns]
#df.columns = df.columns.str.replace(' ', '_')

In [158]:
df.rename(columns = {'ResponseId':'Id'}, inplace = True)

In [170]:
df.loc[1,'Country'] = ['Russia']
#changing value of row

In [171]:
df

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Russia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",XOF\tWest African CFA franc,200000.0,Monthly,NaN,NaN,Firebase;MariaDB;MySQL;PostgreSQL;Redis;SQLite,Firebase;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,NaN,NaN,Django;jQuery;Laravel;React.js;Ruby on Rails,Django;Express;jQuery;Laravel;React.js;Ruby on...,Flutter;Qt,NaN,Git;Unity 3D;Unreal Engine,Docker;Git;Kubernetes,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,FastAPI;Flask,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,Express;Laravel;Spring;Symfony,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0
0,NaN,NaN,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [175]:
filt = (df['Country'] == 'Tuvalu')
df[filt]
#filtering by country

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
61691,I am a student who is learning to code,"Student, part-time",Tuvalu,NaN,NaN,"Professional degree (JD, MD, etc.)",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",9,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell;C;C++;HTML/CSS;Java;JavaSc...,Scala,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,AWS;Oracle Cloud Infrastructure,NaN,Gatsby;jQuery;React.js;Symfony,NaN,.NET Framework;NumPy;Pandas;TensorFlow;Torch/P...,NaN,Docker;Git;Kubernetes,Unreal Engine,Android Studio;Atom;Eclipse;IntelliJ;IPython/J...,NaN,Linux-based,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"Yes, somewhat",Yes,18-24 years old,Man,No,Prefer to self-describe:,"White or of European descent;Or, in your own w...","I am blind / have difficulty seeing;Or, in you...",I have an anxiety disorder,Appropriate in length,Easy,NaN

In [176]:
df.loc[filt, 'ConvertedCompYearly'] = 27000
df[filt]
#update row of filter on a specific column

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
61691,I am a student who is learning to code,"Student, part-time",Tuvalu,NaN,NaN,"Professional degree (JD, MD, etc.)",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",9,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell;C;C++;HTML/CSS;Java;JavaSc...,Scala,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,AWS;Oracle Cloud Infrastructure,NaN,Gatsby;jQuery;React.js;Symfony,NaN,.NET Framework;NumPy;Pandas;TensorFlow;Torch/P...,NaN,Docker;Git;Kubernetes,Unreal Engine,Android Studio;Atom;Eclipse;IntelliJ;IPython/J...,NaN,Linux-based,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"Yes, somewhat",Yes,18-24 years old,Man,No,Prefer to self-describe:,"White or of European descent;Or, in your own w...","I am blind / have difficulty seeing;Or, in you...",I have an anxiety disorder,Appropriate in length,Easy,27000.0

In [179]:
df['Country'].apply(len)
#applies a function to a column

ResponseId
1         6
2        11
3        18
4         7
5        52
         ..
83436     5
83437    24
83438     6
83439     6
0         6
Name: Country, Length: 83440, dtype: int64

In [182]:
df.apply(len)
#apply to all series   == len(df['something'])

MainBranch             83440
Employment             83440
Country                83440
US_State               83440
UK_Country             83440
                       ...
Accessibility          83440
MentalHealth           83440
SurveyLength           83440
SurveyEase             83440
ConvertedCompYearly    83440
Length: 47, dtype: int64

In [184]:
# df.applymap(len) applies to all df

In [186]:
df.rename(columns={'ConvertedCompYearly':'YearlyUSDSalary'})
df.rename(columns={'YearlyUSDSalary':'ConvertedCompYearly'})

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Russia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",XOF\tWest African CFA franc,200000.0,Monthly,NaN,NaN,Firebase;MariaDB;MySQL;PostgreSQL;Redis;SQLite,Firebase;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,NaN,NaN,Django;jQuery;Laravel;React.js;Ruby on Rails,Django;Express;jQuery;Laravel;React.js;Ruby on...,Flutter;Qt,NaN,Git;Unity 3D;Unreal Engine,Docker;Git;Kubernetes,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,FastAPI;Flask,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,Express;Laravel;Spring;Symfony,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0
0,NaN,NaN,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [187]:
df['garbage_info'] = df['US_State'] + ' ' + df['UK_Country']
#combine columns

In [188]:
df

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly,garbage_info
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Russia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0,NaN
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",XOF\tWest African CFA franc,200000.0,Monthly,NaN,NaN,Firebase;MariaDB;MySQL;PostgreSQL;Redis;SQLite,Firebase;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,NaN,NaN,Django;jQuery;Laravel;React.js;Ruby on Rails,Django;Express;jQuery;Laravel;React.js;Ruby on...,Flutter;Qt,NaN,Git;Unity 3D;Unreal Engine,Docker;Git;Kubernetes,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0,NaN
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,FastAPI;Flask,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0,NaN
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0,NaN
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,Express;Laravel;Spring;Symfony,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0,NaN
0,NaN,NaN,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [193]:
df.drop(columns=['UK_Country','US_State','garbage_info'], inplace = True)
#delete columns, lacks inplace

In [194]:
df.append({'Country':'Pascua Island'}, ignore_index = True)
#append a row

,MainBranch,Employment,Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Russia,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,I am a student who is learning to code,"Student, full-time",Netherlands,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,I am a developer by profession,Employed full-time,Austria,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83436,I am a developer by profession,Employed full-time,United States of America,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,FastAPI;Flask,Hadoop;Keras;NumPy;Pandas,Apache Spark;Hadoop;Keras;NumPy;Pandas;TensorFlow,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83437,I am a developer by profession,Employed full-time,Canada,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,NaN,NumPy;Pandas;TensorFlow;Torch/PyTorch,NumPy;Pandas;TensorFlow;Torch/PyTorch,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83438,I am a developer by profession,Employed full-time,Brazil,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,Express;Laravel;Spring;Symfony,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0
83439,NaN,NaN,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83440,NaN,NaN,Pascua Island,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [224]:
pd.set_option('display.max_rows',200)
df_arg[['ConvertedCompYearly','CompTotal','Currency','CompFreq','YearsCode','YearsCodePro']][0:200].sort_values(by='ConvertedCompYearly')

,ConvertedCompYearly,CompTotal,Currency,CompFreq,YearsCode,YearsCodePro
ResponseId,,,,,,
16403,84.0,450.0,ARS\tArgentine peso,Monthly,18,16
8520,132.0,680.0,ARS\tArgentine peso,Monthly,16,11
7518,1944.0,10000.0,ARS\tArgentine peso,Monthly,25,15
10540,4860.0,25000.0,ARS\tArgentine peso,Monthly,7,1
10713,6228.0,32000.0,ARS\tArgentine peso,Monthly,3,Less than 1 year
25763,7392.0,38000.0,ARS\tArgentine peso,Monthly,7,Less than 1 year
28104,7788.0,40000.0,ARS\tArgentine peso,Monthly,3,5
21600,7788.0,40000.0,ARS\tArgentine peso,Monthly,5,Less than 1 year
21413,7788.0,40000.0,ARS\tArgentine peso,Monthly,20,2
17095,7788.0,40000.0,ARS\tArgentine peso,Monthly,NaN,NaN
17927,8172.0,42000.0,ARS\tArgentine peso,Monthly,6,2
25776,10116.0,52000.0,ARS\tArgentine peso,Monthly,8,Less than 1 year
4364,10116.0,52000.0,ARS\tArgentine peso,Monthly,8,4
18978,10950.0,13500.0,ARS\tArgentine peso,Weekly,10,4
7727,11676.0,60000.0,ARS\tArgentine peso,Monthly,6,2
18014,13428.0,69000.0,ARS\tArgentine peso,Monthly,9,7
28846,13620.0,70000.0,ARS\tArgentine peso,Monthly,4,4
27613,13620.0,70000.0,ARS\tArgentine peso,Monthly,21,17
19608,13620.0,70000.0,ARS\tArgentine peso,Monthly,13,2
22194,13620.0,70000.0,ARS\tArgentine peso,Monthly,3,Less than 1 year
29250,13800.0,17000.0,ARS\tArgentine peso,Weekly,5,3
1327,14016.0,72000.0,ARS\tArgentine peso,Monthly,15,15
12395,14400.0,1200.0,USD\tUnited States dollar,Monthly,11,2
29605,14400.0,1200.0,USD\tUnited States dollar,Monthly,9,2
20082,15576.0,80000.0,ARS\tArgentine peso,Monthly,24,16
18484,15960.0,82000.0,ARS\tArgentine peso,Monthly,2,Less than 1 year
20029,16548.0,85000.0,ARS\tArgentine peso,Monthly,4,2
28387,17520.0,90000.0,ARS\tArgentine peso,Monthly,5,1
21168,17520.0,90000.0,ARS\tArgentine peso,Monthly,6,2
6136,18000.0,1500.0,USD\tUnited States dollar,Monthly,8,4
27925,19464.0,100000.0,ARS\tArgentine peso,Monthly,37,20
5717,19464.0,100000.0,ARS\tArgentine peso,Monthly,2,1
21406,19464.0,100000.0,ARS\tArgentine peso,Monthly,20,14
19454,19464.0,100000.0,ARS\tArgentine peso,Monthly,3,2
18781,19464.0,100000.0,ARS\tArgentine peso,Monthly,27,13
16090,19464.0,100000.0,ARS\tArgentine peso,Monthly,14,14
21593,20436.0,105000.0,ARS\tArgentine peso,Monthly,11,4
28302,21408.0,110000.0,ARS\tArgentine peso,Monthly,7,4
28732,21408.0,110000.0,ARS\tArgentine peso,Monthly,22,22
22260,21600.0,1800.0,USD\tUnited States dollar,Monthly,20,13
28276,23352.0,120000.0,ARS\tArgentine peso,Monthly,27,15
25366,23352.0,120000.0,ARS\tArgentine peso,Monthly,7,4
19106,23352.0,120000.0,ARS\tArgentine peso,Monthly,15,5
28843,24132.0,124000.0,ARS\tArgentine peso,Monthly,15,15
28287,24324.0,125000.0,ARS\tArgentine peso,Monthly,10,5
29539,24324.0,125000.0,ARS\tArgentine peso,Monthly,12,8
19478,24324.0,125000.0,ARS\tArgentine peso,Monthly,35,30
20319,25000.0,25000.0,USD\tUnited States dollar,Yearly,22,4
17976,25296.0,130000.0,ARS\tArgentine peso,Monthly,15,4
10935,25296.0,130000.0,ARS\tArgentine peso,Monthly,9,4
19189,25950.0,1600000.0,ARS\tArgentine peso,Yearly,3,1
25510,26400.0,2200.0,USD\tUnited States dollar,Monthly,10,7
5589,26400.0,2200.0,USD\tUnited States dollar,Monthly,5,2
29479,27252.0,140000.0,ARS\tArgentine peso,Monthly,17,14
26017,27600.0,2300.0,USD\tUnited States dollar,Monthly,25,16
20100,28224.0,145000.0,ARS\tArgentine peso,Monthly,6,3
29205,29196.0,150000.0,ARS\tArgentine peso,Monthly,25,23
21392,29196.0,150000.0,ARS\tArgentine peso,Monthly,6,1
21233,29196.0,150000.0,ARS\tArgentine peso,Monthly,12,12
26746,29196.0,150000.0,ARS\tArgentine peso,Monthly,8,7
27952,29196.0,150000.0,ARS\tArgentine peso,Monthly,36,20
10421,29196.0,150000.0,ARS\tArgentine peso,Monthly,3,1
27823,29196.0,150000.0,ARS\tArgentine peso,Monthly,11,5
27818,29196.0,150000.0,ARS\tArgentine peso,Monthly,15,7
28067,30000.0,2500.0,USD\tUnited States dollar,Monthly,20,15
3888,31140.0,160000.0,ARS\tArgentine peso,Monthly,8,4
21337,31140.0,160000.0,ARS\tArgentine peso,Monthly,37,32
28826,31140.0,160000.0,ARS\tArgentine peso,Monthly,8,6
5810,31140.0,160000.0,ARS\tArgentine peso,Monthly,7,6
28216,34548.0,177490.0,ARS\tArgentine peso,Monthly,7,4
29340,35028.0,180000.0,ARS\tArgentine peso,Monthly,5,5
28060,35028.0,180000.0,ARS\tArgentine peso,Monthly,30,15
21497,35028.0,180000.0,ARS\tArgentine peso,Monthly,10,10
18894,36000.0,36000.0,USD\tUnited States dollar,Yearly,21,12
28001,36000.0,3000.0,USD\tUnited States dollar,Monthly,8,7
8744,36000.0,3000.0,USD\tUnited States dollar,Monthly,4,1
8565,36948.0,13440.0,BRL\tBrazilian real,Monthly,10,8
29084,36984.0,190000.0,ARS\tArgentine peso,Monthly,7,4
19743,37200.0,3100.0,USD\tUnited States dollar,Monthly,6,2
19842,38400.0,3200.0,USD\tUnited States dollar,Monthly,9,6
28360,38928.0,200000.0,ARS\tArgentine peso,Monthly,10,10
27117,38928.0,200000.0,ARS\tArgentine peso,Monthly,10,3
27566,38928.0,200000.0,ARS\tArgentine peso,Monthly,14,10
28235,38928.0,200000.0,ARS\tArgentine peso,Monthly,16,10
20822,38928.0,200000.0,ARS\tArgentine peso,Monthly,35,32
29728,38928.0,200000.0,ARS\tArgentine peso,Monthly,25,30
1928,39347.0,2426000.0,ARS\tArgentine peso,Yearly,10,2
6368,40872.0,210000.0,ARS\tArgentine peso,Monthly,14,14
7793,40872.0,210000.0,ARS\tArgentine peso,Monthly,31,20
10203,42816.0,220000.0,ARS\tArgentine peso,Monthly,38,22
27600,42816.0,220000.0,ARS\tArgentine peso,Monthly,30,23
2101,43200.0,3600.0,USD\tUnited States dollar,Monthly,12,9
29165,45000.0,900.0,USD\tUnited States dollar,Weekly,8,2
20568,46800.0,3900.0,USD\tUnited States dollar,Monthly,10,8
29360,47040.0,3920.0,USD\tUnited States dollar,Monthly,4,4
21436,48000.0,4000.0,USD\tUnited States dollar,Monthly,11,8
28567,48660.0,250000.0,ARS\tArgentine peso,Monthly,25,11
22114,48660.0,250000.0,ARS\tArgentine peso,Monthly,25,20
27317,48660.0,250000.0,ARS\tArgentine peso,Monthly,18,16
27135,48660.0,250000.0,ARS\tArgentine peso,Monthly,17,15
20982,50400.0,4200.0,USD\tUnited States dollar,Monthly,12,5
5150,51600.0,4300.0,USD\tUnited States dollar,Monthly,25,23
28606,52548.0,270000.0,ARS\tArgentine peso,Monthly,20,10
28639,56750.0,70000.0,ARS\tArgentine peso,Weekly,20,19
1971,56832.0,292000.0,ARS\tArgentine peso,Monthly,10,7
19551,58188.0,299000.0,ARS\tArgentine peso,Monthly,8,7
10484,58392.0,300000.0,ARS\tArgentine peso,Monthly,31,15
16521,60000.0,5000.0,USD\tUnited States dollar,Monthly,30,22
21954,60000.0,60000.0,USD\tUnited States dollar,Yearly,6,6
3141,60000.0,5000.0,USD\tUnited States dollar,Monthly,8,6
10010,60000.0,60000.0,USD\tUnited States dollar,Yearly,12,7
19266,60000.0,5000.0,USD\tUnited States dollar,Monthly,28,15
29367,62040.0,4000.0,GBP\tPound sterling,Monthly,12,8
1842,63252.0,325000.0,ARS\tArgentine peso,Monthly,7,6
5630,66000.0,5500.0,USD\tUnited States dollar,Monthly,20,15
28392,68124.0,350000.0,ARS\tArgentine peso,Monthly,25,18
28163,72000.0,6000.0,USD\tUnited States dollar,Monthly,21,17
6104,72000.0,72000.0,USD\tUnited States dollar,Yearly,15,7
28554,72000.0,6000.0,USD\tUnited States dollar,Monthly,16,12
290,75000.0,75000.0,USD\tUnited States dollar,Yearly,5,Less than 1 year
20074,75600.0,6300.0,USD\tUnited States dollar,Monthly,22,22
27846,77856.0,400000.0,ARS\tArgentine peso,Monthly,20,20
27640,84000.0,7000.0,USD\tUnited States dollar,Monthly,15,10
26582,97308.0,500000.0,ARS\tArgentine peso,Monthly,40,30
8981,97308.0,500000.0,ARS\tArgentine peso,Monthly,16,11
27365,97308.0,500000.0,ARS\tArgentine peso,Monthly,13,9
25519,97308.0,500000.0,ARS\tArgentine peso,Monthly,28,18
20077,97308.0,500000.0,ARS\tArgentine peso,Monthly,25,25
17303,97313.0,6000000.0,ARS\tArgentine peso,Yearly,14,13
1202,100000.0,100000.0,USD\tUnited States dollar,Yearly,17,14
19278,106212.0,545700.0,ARS\tArgentine peso,Monthly,20,16
29688,116772.0,600000.0,ARS\tArgentine peso,Monthly,30,25
18375,116772.0,600000.0,ARS\tArgentine peso,Monthly,15,13
19149,116772.0,600000.0,ARS\tArgentine peso,Monthly,15,8
18787,120000.0,120000.0,USD\tUnited States dollar,Yearly,37,25
4570,128340.0,659424.0,ARS\tArgentine peso,Monthly,17,15
8335,150000.0,150000.0,USD\tUnited States dollar,Yearly,14,13
18974,240000.0,240000.0,USD\tUnited States dollar,Yearly,11,11
484,279774.0,17250000.0,ARS\tArgentine peso,Yearly,20,18
24459,480000.0,40000.0,USD\tUnited States dollar,Monthly,8,3
1046,NaN,NaN,NaN,NaN,3,NaN
1742,NaN,NaN,NaN,NaN,NaN,NaN
4536,NaN,NaN,ARS\tArgentine peso,Monthly,1,Less than 1 year
6490,NaN,NaN,USD\tUnited States dollar,NaN,Less than 1 year,Less than 1 year
7293,NaN,NaN,USD\tUnited States dollar,NaN,15,10
8441,NaN,NaN,NaN,NaN,2,NaN
9255,NaN,NaN,NaN,NaN,NaN,NaN
9484,NaN,NaN,NaN,NaN,Less than 1 year,NaN
9687,NaN,NaN,NaN,NaN,NaN,NaN
10060,NaN,NaN,NaN,NaN,1,NaN
10074,NaN,NaN,NaN,NaN,13,NaN
10313,NaN,NaN,NaN,NaN,Less than 1 year,NaN
10739,NaN,NaN,NaN,NaN,NaN,NaN
10836,NaN,NaN,USD\tUnited States dollar,NaN,8,7
10912,NaN,NaN,ARS\tArgentine peso,Monthly,8,4
11596,NaN,NaN,NaN,NaN,2,NaN
12525,NaN,NaN,NaN,NaN,NaN,NaN
14071,NaN,NaN,NaN,NaN,20,NaN
16284,NaN,NaN,ARS\tArgentine peso,Monthly,5,3
17473,NaN,NaN,ARS\tArgentine peso,Monthly,15,5
17781,NaN,NaN,NaN,NaN,1,NaN
18278,NaN,NaN,NaN,NaN,NaN,NaN
18760,NaN,NaN,NaN,NaN,5,NaN
19108,NaN,NaN,NaN,NaN,25,NaN
19323,NaN,NaN,ARS\tArgentine peso,NaN,20,15
19496,NaN,NaN,ARS\tArgentine peso,NaN,8,5
20197,NaN,NaN,NaN,NaN,20,NaN
20564,NaN,NaN,NaN,NaN,6,NaN
20792,NaN,NaN,NaN,NaN,4,NaN
21046,NaN,NaN,NaN,NaN,5,NaN
21174,NaN,NaN,NaN,NaN,5,NaN
21252,NaN,NaN,NaN,NaN,6,NaN
21299,NaN,NaN,NaN,NaN,2,NaN
21414,NaN,NaN,NaN,NaN,25,20
21708,NaN,NaN,NaN,NaN,4,NaN
21828,NaN,NaN,NaN,NaN,4,NaN
21920,NaN,NaN,NaN,NaN,7,NaN
22112,NaN,NaN,NaN,NaN,NaN,NaN
22257,NaN,NaN,NaN,NaN,4,NaN
22320,NaN,NaN,ARS\tArgentine peso,NaN,11,8
23447,NaN,NaN,ARS\tArgentine peso,Monthly,22,20
23476,NaN,NaN,NaN,NaN,5,NaN
24164,NaN,NaN,NaN,NaN,2,NaN
25122,NaN,NaN,NaN,NaN,1,NaN
25903,NaN,NaN,ARS\tArgentine peso,NaN,27,20
26631,NaN,NaN,ARS\tArgentine peso,NaN,8,3
27127,NaN,NaN,ARS\tArgentine peso,NaN,35,20
27151,NaN,NaN,NaN,NaN,3,NaN
27184,NaN,NaN,ARS\tArgentine peso,Monthly,20,18
27270,NaN,NaN,ARS\tArgentine peso,Monthly,15,8
27386,NaN,NaN,ARS\tArgentine peso,NaN,20,6
27474,NaN,NaN,NaN,NaN,Less than 1 year,NaN
27545,NaN,NaN,USD\tUnited States dollar,NaN,7,2
27709,NaN,NaN,ARS\tArgentine peso,Monthly,15,12
28129,NaN,NaN,VES\tVenezuelan bolivar,Monthly,12,7
28489,NaN,NaN,ARS\tArgentine peso,NaN,35,25
28964,NaN,NaN,USD\tUnited States dollar,NaN,26,17
29402,NaN,NaN,NaN,NaN,20,NaN
29417,NaN,NaN,NaN,NaN,10,5
29704,NaN,NaN,ARS\tArgentine peso,NaN,7,3

In [229]:
df_arg['ConvertedCompYearly'].median()

35712.0

In [230]:
df['ConvertedCompYearly'].median()

56211.0

In [231]:
df_ds_notnan['ConvertedCompYearly'].median()

54049.0

In [232]:
df.median()

CompTotal              67000.0
ConvertedCompYearly    56211.0
dtype: float64

In [233]:
df_arg.median()

C:\Users\Emilio\anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1113: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

US_State                    NaN
UK_Country                  NaN
CompTotal              100000.0
ConvertedCompYearly     35712.0
dtype: float64

In [234]:
df.describe()

          CompTotal  ConvertedCompYearly
count  4.718300e+04         4.684500e+04
mean   2.119407e+69         1.184242e+05
std    4.603702e+71         5.272889e+05
min    0.000000e+00         1.000000e+00
25%    1.600000e+04         2.702500e+04
50%    6.700000e+04         5.621100e+04
75%    1.400000e+05         1.000000e+05
max    1.000000e+74         4.524131e+07

In [237]:
df_arg.describe()

          CompTotal  ConvertedCompYearly
count  4.120000e+02           410.000000
mean   3.356080e+05         45991.175610
std    1.255272e+06         43648.370727
min    0.000000e+00            84.000000
25%    3.500000e+04         19464.000000
50%    1.000000e+05         35712.000000
75%    2.000000e+05         58392.000000
max    1.725000e+07        480000.000000

In [238]:
df_ds_notnan.describe()

          CompTotal  ConvertedCompYearly
count  3.670000e+02         3.670000e+02
mean   2.094396e+06         1.213893e+05
std    1.255327e+07         4.543321e+05
min    1.800000e+01         4.800000e+01
25%    3.675000e+04         2.592700e+04
50%    8.000000e+04         5.404900e+04
75%    2.215000e+05         1.084070e+05
max    1.700000e+08         8.078700e+06

In [239]:
df['Country'].value_counts()

United States of America                                15288
India                                                   10511
Germany                                                  5625
United Kingdom of Great Britain and Northern Ireland     4475
Canada                                                   3012
France                                                   2708
Brazil                                                   2254
Poland                                                   1805
Netherlands                                              1772
Italy                                                    1666
Australia                                                1646
Spain                                                    1485
Russian Federation                                       1474
Sweden                                                   1196
China                                                    1055
Turkey                                                   1054
Switzerland                                               922
Israel                                                    913
Iran, Islamic Republic of...                              900
Pakistan                                                  838
Austria                                                   808
Czech Republic                                            792
Ukraine                                                   770
Bangladesh                                                704
Belgium                                                   697
Mexico                                                    695
Romania                                                   650
Indonesia                                                 632
Greece                                                    603
Norway                                                    602
Denmark                                                   599
Argentina                                                 587
South Africa                                              571
Portugal                                                  530
Finland                                                   528
New Zealand                                               522
Egypt                                                     521
Hungary                                                   478
Japan                                                     429
Nigeria                                                   409
Bulgaria                                                  402
Sri Lanka                                                 396
Ireland                                                   386
Viet Nam                                                  386
Philippines                                               382
Colombia                                                  381
Singapore                                                 339
Nepal                                                     337
Malaysia                                                  333
Serbia                                                    310
Taiwan                                                    302
Kenya                                                     263
Slovakia                                                  251
Croatia                                                   250
Slovenia                                                  235
Chile                                                     230
Lithuania                                                 208
Morocco                                                   204
Hong Kong (S.A.R.)                                        198
South Korea                                               189
Thailand                                                  184
United Arab Emirates                                      182
Belarus                                                   165
Georgia                                                   161
Tunisia                                                   150
Peru                                                      147
Uruguay                                                   144
Saudi Arabia                                              137
Bosnia and Herzegovina                                    130
Estonia                                                   130
Lebanon                                                   113
Latvia                                                    107
Dominican Republic                                        104
Venezuela, Bolivarian Republic of...                      104
Ecuador                                                   103
Armenia                                                    92
Ghana                                                      91
Costa Rica                                                 77
Iraq                                                       76
Albania                                                    73
Jordan                                                     72
Ethiopia                                                   69
Uzbekistan                                                 68
Afghanistan                                                65
Kazakhstan                                                 65
Azerbaijan                                                 64
Uganda                                                     63
Guatemala                                                  58
Cyprus                                                     56
Myanmar                                                    55
Republic of Moldova                                        55
Republic of Korea                                          54
Nomadic                                                    54
The former Yugoslav Republic of Macedonia                  54
Syrian Arab Republic                                       51
Luxembourg                                                 51
Bolivia                                                    48
Paraguay                                                   47
Algeria                                                    46
Kosovo                                                     45
United Republic of Tanzania                                43
Iceland                                                    43
Malta                                                      42
Cameroon                                                   38
Zimbabwe                                                   36
Cambodia                                                   35
Cuba                                                       34
Rwanda                                                     34
El Salvador                                                32
Mauritius                                                  31
Panama                                                     31
Qatar                                                      29
Kuwait                                                     29
Bahrain                                                    28
Senegal                                                    28
Angola                                                     27
Sudan                                                      27
Palestine                                                  25
Honduras                                                   24
Zambia                                                     22
Mongolia                                                   21
Kyrgyzstan                                                 21
Yemen                                                      20
Oman                                                       20
Jamaica                                                    20
Trinidad and Tobago                                        20
Madagascar                                                 18
Nicaragua                                                  18
Côte d'Ivoire                                              17
Montenegro                                                 17
Maldives                                                   16
Benin                                                      15
Turkmenistan                                               13
Andorra                                                    12
Barbados                                                   12
Namibia                                                    12
Mozambique                                                 12
Congo, Republic of the...                                  12
Libyan Arab Jamahiriya                                     11
Malawi                                                     11
Swaziland                                                  10
Democratic Republic of the Congo                           10
Tajikistan                                                  9
Guyana                                                      7
Bahamas                                                     7
Togo                                                        7
Somalia                                                     7
North Korea                                                 6
Botswana                                                    6
Cape Verde                                                  6
Belize                                                      5
Burundi                                                     5
Bhutan                                                      5
Suriname                                                    5
Haiti                                                       5
Isle of Man                                                 5
Mauritania                                                  5
Burkina Faso                                                4
Lesotho                                                     4
Lao People's Democratic Republic                            4
Fiji                                                        4
Liberia                                                     3
Saint Lucia                                                 3
Central African Republic                                    3
Niger                                                       3
Djibouti                                                    3
Monaco                                                      2
Guinea                                                      2
Sierra Leone                                                2
San Marino                                                  2
Russia                                                      2
Gambia                                                      2
Mali                                                        2
Chad                                                        2
Micronesia, Federated States of...                          2
Tuvalu                                                      1
Saint Vincent and the Grenadines                            1
Papua New Guinea                                            1
Dominica                                                    1
Saint Kitts and Nevis                                       1
Brunei Darussalam                                           1
Liechtenstein                                               1
Name: Country, dtype: int64

In [241]:
df_country = df.groupby(['Country'])

In [249]:
df_ar = df_country.get_group('Argentina')

In [253]:
df_ar.loc[df['Country']=='Argentina']['YearsCodePro'].value_counts()

2                   43
3                   37
4                   35
15                  33
Less than 1 year    28
5                   26
10                  25
8                   24
6                   23
20                  23
7                   22
1                   22
25                  18
12                  15
11                  12
9                   10
14                  10
18                  10
23                   9
13                   9
17                   8
30                   6
16                   6
22                   5
21                   4
19                   3
28                   2
32                   2
26                   2
24                   2
31                   1
35                   1
34                   1
Name: YearsCodePro, dtype: int64